name = "ocif-validator-poc"
pages_build_output_dir = "dist"
compatibility_date = "2024-05-14" # Recommended: Use a recent date

[build]
command = "npm run build"
# watch_dir = "src" # Optional: uncomment if using `wrangler pages dev` 